QuizTaker/QuizBuilder/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'quizbuilder'

urlpatterns = [

    path("login/", views.login, name="quizbuilder_login"),
    path("logout/", views.logout, name="quizbuilder_logout"),
    path("signup/", views.signup, name="quizbuilder_signup"),


    path("home/", views.home, name="quizbuilder_home"),
    path("quizzes/", views.quizzes, name="quizbuilder_quizzes"),
    path("pricing/", views.pricing, name="quizbuilder_pricing"),
    path("about/", views.about, name="quizbuilder_about"),
    path("contact/", views.contact, name="quizbuilder_contact"),



    path("quiz/", views.quiz, name="quizbuilder_quiz"),
    path("dashboard/", views.dashboard, name="quizbuilder_dashboard"),
    path("create/", views.create_quiz, name="quizbuilder_create"),

]

QuizTaker/QuizTaker/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("admin/:", admin.site.urls),
    path("", views.index, name="site_homepage"),
]

QuizTaker/QuizBuilder/models.py
from django.db import models
import uuid

# Create your models here.

class BaseModel(models.Model):
    # base class fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # set tbase model as abstract so this model will
    # not be used to crete any dtabase table. Instead, 
    # when it is used as a base class for other models, 
    # its fields will be added to those of the child class.
    class Meta:
        abstract = True

class User(BaseModel):
    email = models.EmailField(unique=True, max_length=255, null=False)
    name  = models.CharField(max_length=65, null=False)
    password = models.CharField(max_length=100, null=False)
    user_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False, db_column='user_id')

    class Meta:
        verbose_name_plural = "Users"
        db_table = "quiz_builder_users"

    def __str__(self):
        return f'{self.name}'

class Quiz(BaseModel):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, db_column='user_id')
    quiz_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, db_column='quiz_id')
    quiz_title = models.CharField(max_length=255, null=False)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Quizs"
        db_table = "quiz_builder_quiz"

    
    def __str__(self):
        return f'{self.quiz_title}'

class QuizQuestion(BaseModel):
    quiz_id = models.ForeignKey(Quiz, on_delete=models.CASCADE, db_column='quiz_id')
    question_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    question = models.CharField(max_length=255, null=False)
    option_a = models.CharField(max_length=255, null=False)
    option_b = models.CharField(max_length=255, null=False)
    option_c = models.CharField(max_length=255, null=False)
    option_d = models.CharField(max_length=255, null=False)
    correct_answer = models.CharField(max_length=1, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], null=False)

    class Meta:
        verbose_name_plural = "Quiz Questions"
        db_table = "quiz_builder_quiz_question"

    def __str__(self):
        return f'{self.question}'

QuizTaker/QuizBuilder/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
import json
from .api_quiz_builder import api_create_quiz, api_create_user
from django.views.decorators.csrf import csrf_exempt

def home(request):
    return render(request=request,template_name="QuizBuilder/home.html")

def quizzes(request):
    return render(request=request,template_name="QuizBuilder/quizzes.html")

def pricing(request):
    return render(request=request,template_name="QuizBuilder/pricing.html")

def about(request):
    return render(request=request,template_name="QuizBuilder/about.html")

def contact(request):
    return render(request=request,template_name="QuizBuilder/contact.html")

@csrf_exempt
def signup(request):
    if request.method == "POST":
        print(request.POST)
        
        try:
            data = json.loads(request.body.decode("utf-8"))

        except json.JSONDecodeError:
            response_data = {}
            response_data["status"] = "error"
            response_data["message"] = "please provide valid json"
            return JsonResponse(response_data)

        print(data)
        # response_data = api_create_user(data)
        print(request.POST)

    return render(request=request,template_name="QuizBuilder/signup.html")

def login(request):
    return render(request=request,template_name="QuizBuilder/login.html")

def logout(request):
    return render(request=request,template_name="QuizBuilder/signup.html")

def quiz(request):
    #return HttpResponse("Hello, world. You"re at the quiz.")
    return render(request=request,template_name="QuizBuilder/take_quiz.html")

def dashboard(request):
    #return HttpResponse("Hello, world. You"re at the quiz.")
    return render(request=request,template_name="QuizBuilder/dashboard.html")

@csrf_exempt
def create_quiz(request):

    if request.method == "POST":
        
        try:
            data = json.loads(request.body.decode("utf-8"))

        except json.JSONDecodeError:
            response_data = {}
            response_data["status"] = "error"
            response_data["message"] = "please provide valid json"
            return JsonResponse(response_data)

        response_data = api_create_quiz(data, email='wdw@abc.com')

        return JsonResponse(response_data)

        return render(request=request,template_name="QuizBuilder/create_quiz.html",context=data)

    return render(request=request,template_name="QuizBuilder/create_quiz.html")

QuizTaker/QuizTaker/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    # return HttpResponse("Hello, world. You're at the polls index.")
    return render(request=request,template_name='QuizTaker/home.html')

QuizTaker/QuizBuilder/templates/QuizBuilder/about.html
<!-- user signup form -->

{% extends "QuizBuilder/base.html" %}

{% block title %} About {% endblock %}

<!-- include navbar -->
{% block navbar %}

    {% include "QuizBuilder/navbar.html" %}

{% endblock %}

<!-- about page -->
{% block content %}

    <div>
        <h1>This is About Page</h1>
    </div>

{% endblock %}

<!-- include footer -->
{% block footer %}

    {% include "QuizBuilder/footer.html" %}

{% endblock %}

QuizTaker/QuizBuilder/templates/QuizBuilder/base.html
<!-- base html templte for all website (not for webapp) html files -->

{% load static %}

{% csrf_token %}

<!-- display message -->
{% if messages %}
    <ul class="messages mb-0">
        {% for message in messages %}
        <div  {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            <div class="alert alert-success alert-dismissible mb-0">
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                <strong>New message!</strong> {{ message }}
              </div>
        </div>
        
        {% endfor %}
    </ul>
{% endif %}

<!DOCTYPE html>
<html lang="en">

   <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>{% block title %}QuizTaker - Home{% endblock %}</title>
      <!-- Include Tailwind CSS CDN or link to your compiled CSS file -->
      <script src="https://cdn.tailwindcss.com"></script>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" />
   </head>

   <body>

        <div id="navbar">
            {% block navbar %}{% endblock %}
        </div>

        <div id="body">
            {% block content %}{% endblock %}
        </div>

        <div id="footer">
            {% block footer %}{% endblock %}
        </div>

    </body>
</html>

QuizTaker/QuizBuilder/templates/QuizBuilder/contact.html
<!-- user signup form -->

{% extends "QuizBuilder/base.html" %}

{% block title %} Contact {% endblock %}

<!-- include navbar -->
{% block navbar %}

    {% include "QuizBuilder/navbar.html" %}

{% endblock %}

<!-- Contact page -->
{% block content %}

    <div>
        <h1>This is Contact Page</h1>
    </div>

{% endblock %}

<!-- include footer -->
{% block footer %}

    {% include "QuizBuilder/footer.html" %}

{% endblock %}

QuizTaker/QuizBuilder/templates/QuizBuilder/footer.html
    <!-- Footer Section -->
    <div class="px-2">
        <footer class="bg-gray-800 text-white text-center p-4">
          <div class="container mx-auto text-center">
            <p>&copy; 2023 QuizTaker. All rights reserved.</p>
          </div>
        </footer>
      </div>

QuizTaker/QuizBuilder/templates/QuizBuilder/home.html
<!-- user signup form -->

{% extends "QuizBuilder/base.html" %}

{% block title %} Home {% endblock %}

<!-- include navbar -->
{% block navbar %}

    {% include "QuizBuilder/navbar.html" %}

{% endblock %}

<!-- Home page -->
{% block content %}

    <div>
        <h1>This is Home Page</h1>
    </div>

{% endblock %}

<!-- include footer -->
{% block footer %}

    {% include "QuizBuilder/footer.html" %}

{% endblock %}

QuizTaker/QuizBuilder/templates/QuizBuilder/navbar.html
{% extends "QuizBuilder/base.html" %}

{% load static %}

{% block title %} Navbar {% endblock %}

<!-- navbar -->
{% block navbar %}

<nav class="relative px-4 py-4 flex justify-between items-center bg-white">
      <a class="text-3xl font-bold leading-none" href="#">
        <img class="h-10 w-15" src="{% static 'QuizTaker/img/quiztaker-high-resolution-logo-black-on-transparent-background.png' %}" alt="QuizTaker Logo" />
      </a>
      <div class="lg:hidden">
        <button class="navbar-burger flex items-center text-blue-600 p-3">
          <svg class="block h-4 w-4 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <title>QuizTaker</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
          </svg>
        </button>
      </div>
      <ul class="hidden absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 lg:flex lg:mx-auto lg:flex lg:items-center lg:w-auto lg:space-x-6">
        <li>
          <a class="text-sm text-gray-400 hover:text-gray-500" href="{% url 'quizbuilder:quizbuilder_home' %}">Home</a>
        </li>
        <li class="text-gray-300">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" class="w-4 h-4 current-fill" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
          </svg>
        </li>
        <li>
          <a class="text-sm text-blue-600 font-bold" href="{% url 'quizbuilder:quizbuilder_quizzes' %}">Quizzes</a>
        </li>
        <li class="text-gray-300">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" class="w-4 h-4 current-fill" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
          </svg>
        </li>
        <li>
          <a class="text-sm text-gray-400 hover:text-gray-500" href="{% url 'quizbuilder:quizbuilder_pricing' %}">Pricing</a>
        </li>
        <li class="text-gray-300">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" class="w-4 h-4 current-fill" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
          </svg>
        </li>
        <li>
          <a class="text-sm text-gray-400 hover:text-gray-500" href="{% url 'quizbuilder:quizbuilder_about' %}">About</a>
        </li>
        <li class="text-gray-300">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" class="w-4 h-4 current-fill" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
          </svg>
        </li>
        <li>
          <a class="text-sm text-gray-400 hover:text-gray-500" href="{% url 'quizbuilder:quizbuilder_contact' %}">Contact</a>
        </li>
      </ul>
      <div class="hidden lg:block">
        <a class="lg:ml-auto lg:mr-2 py-2 px-6 bg-gray-50 hover:bg-gray-100 text-sm text-gray-900 font-bold  rounded-xl transition duration-200" href="{% url 'quizbuilder:quizbuilder_login' %}">Log In</a>
        <a class="lg:ml-auto lg:mr-2 py-2 px-6 bg-blue-500 hover:bg-blue-600 text-sm text-white font-bold rounded-xl transition duration-200" href="{% url 'quizbuilder:quizbuilder_signup' %}">Sign up</a>
      </div>
    </nav>

    <div class="navbar-menu relative z-50 hidden">
      <div class="navbar-backdrop fixed inset-0 bg-gray-800 opacity-25"></div>
      <nav class="fixed top-0 left-0 bottom-0 flex flex-col w-5/6 max-w-sm py-6 px-6 bg-white border-r overflow-y-auto">
        <div class="flex items-center mb-8">
          <a class="mr-auto text-3xl font-bold leading-none" href="#">QuizTaker </a>
          <button class="navbar-close">
            <svg class="h-6 w-6 text-gray-400 cursor-pointer hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
          </button>
        </div>
        <div>
          <ul>
            <li class="mb-1">
              <a class="block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded" href="{% url 'quizbuilder:quizbuilder_home' %}">Home</a>
            </li>
            <li class="mb-1">
              <a class="block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded" href="{% url 'quizbuilder:quizbuilder_quizzes' %}">Quizzes</a>
            </li>
            <li class="mb-1">
              <a class="block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded" href="{% url 'quizbuilder:quizbuilder_pricing' %}">Pricing</a>
            </li>
            <li class="mb-1">
              <a class="block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded" href="{% url 'quizbuilder:quizbuilder_about' %}">About</a>
            </li>
            <li class="mb-1">
              <a class="block p-4 text-sm font-semibold text-gray-400 hover:bg-blue-50 hover:text-blue-600 rounded" href="{% url 'quizbuilder:quizbuilder_contact' %}">Contact</a>
            </li>
          </ul>
        </div>
        <div class="mt-auto">
          <div class="pt-6">
            <a class="block px-4 py-3 mb-3 leading-loose text-xs text-center font-semibold leading-none bg-gray-50 hover:bg-gray-100 rounded-xl" href="{% url 'quizbuilder:quizbuilder_login' %}">Log In</a>
            <a class="block px-4 py-3 mb-2 leading-loose text-xs text-center text-white font-semibold bg-blue-600 hover:bg-blue-700  rounded-xl" href="{% url 'quizbuilder:quizbuilder_signup' %}">Sign Up</a>
          </div>
          <p class="my-4 text-xs text-center text-gray-400">
            <span>© 2023 QuizTaker. All rights reserved.</span>
          </p>
        </div>
      </nav>
    </div>

    <!-- Hero Section -->


    <script>

      // Burger menus
      document.addEventListener('DOMContentLoaded', function() {
        // open
        const burger = document.querySelectorAll('.navbar-burger');
        const menu = document.querySelectorAll('.navbar-menu');
        if (burger.length && menu.length) {
          for (var i = 0; i < burger.length; i++) {
            burger[i].addEventListener('click', function() {
              for (var j = 0; j < menu.length; j++) {
                menu[j].classList.toggle('hidden');
              }
            });
          }
        }
        // close
        const close = document.querySelectorAll('.navbar-close');
        const backdrop = document.querySelectorAll('.navbar-backdrop');
        if (close.length) {
          for (var i = 0; i < close.length; i++) {
            close[i].addEventListener('click', function() {
              for (var j = 0; j < menu.length; j++) {
                menu[j].classList.toggle('hidden');
              }
            });
          }
        }
        if (backdrop.length) {
          for (var i = 0; i < backdrop.length; i++) {
            backdrop[i].addEventListener('click', function() {
              for (var j = 0; j < menu.length; j++) {
                menu[j].classList.toggle('hidden');
              }
            });
          }
        }
      });
    </script>
{% endblock %}

QuizTaker/QuizBuilder/templates/QuizBuilder/pricing.html
<!-- user signup form -->

{% extends "QuizBuilder/base.html" %}

{% block title %} About {% endblock %}

<!-- include navbar -->
{% block navbar %}

    {% include "QuizBuilder/navbar.html" %}

{% endblock %}

<!-- Pricing page -->
{% block content %}

    <div>
        <h1>This is Pricing Page</h1>
    </div>

{% endblock %}

<!-- include footer -->
{% block footer %}

{% include "QuizBuilder/footer.html" %}

{% endblock %}

QuizTaker/QuizBuilder/templates/QuizBuilder/quizzes.html
<!-- user signup form -->

{% extends "QuizBuilder/base.html" %}

{% block title %} About {% endblock %}

<!-- include navbar -->
{% block navbar %}

    {% include "QuizBuilder/navbar.html" %}

{% endblock %}

<!-- Quizzes page -->
{% block content %}

    <div>
        <h1>This is Quizzes Page</h1>
    </div>

{% endblock %}

<!-- include footer -->
{% block footer %}

    {% include "QuizBuilder/footer.html" %}

{% endblock %}

QuizTaker/QuizBuilder/templates/QuizBuilder/signup.html
<!-- user signup form -->

{% extends "QuizBuilder/base.html" %}

{% block title %} SignUp {% endblock %}

<!-- include navbar -->
{% block navbar %}

    {% include "QuizBuilder/navbar.html" %}

{% endblock %}

<!-- include signup form -->
{% block content %}

        <div class="bg-grey-lighter min-h-screen flex flex-col bg-violet-600 rounded-t-lg mx-2 px-2">
            <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2 round-xl">
                <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
                    <h1 class="mb-8 text-3xl text-center">Sign up</h1>
                    <form action="{% url 'quizbuilder:quizbuilder_signup' %}" method="post">
                    
                    {% csrf_token %}

                    <input 
                        type="text"
                        class="block border border-grey-light w-full p-3 rounded mb-4"
                        name="fullname"
                        placeholder="Full Name" />
        
                    <input 
                        type="text"
                        class="block border border-grey-light w-full p-3 rounded mb-4"
                        name="email"
                        placeholder="Email" />
        
                    <input 
                        type="password"
                        class="block border border-grey-light w-full p-3 rounded mb-4"
                        name="password"
                        placeholder="Password" />
                    <input 
                        type="password"
                        class="block border border-grey-light w-full p-3 rounded mb-4"
                        name="confirm_password"
                        placeholder="Confirm Password" />
        
                    <button
                        type="submit"
                        class="w-full text-center text-xl py-3 rounded-xl bg-blue-600 text-white hover:bg-violet-700 focus:outline-none my-1"
                    >Create Account</button>

                    </form>
        
                    <div class="text-center text-sm text-grey-dark mt-4">
                        by signing up, you agree to the 
                        <a class="no-underline border-b border-grey-dark text-grey-dark" href="#">
                            Terms of Service
                        </a> and 
                        <a class="no-underline border-b border-grey-dark text-grey-dark" href="#">
                            Privacy Policy
                        </a>
                    </div>
                </div>
        
                <div class="text-white mt-6">
                    Already have an account? 
                    <a class="no-underline border-b border-blue text-blue" href="{% url 'quizbuilder:quizbuilder_login' %}">
                        Log in
                    </a>.
                </div>
            </div>
        </div>

{% endblock %}

<!-- include footer -->
{% block footer %}

    {% include "QuizBuilder/footer.html" %}

{% endblock %}